# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI-CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - Readme.md
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
env:
 AZURE_RG: github-actions-staged
 AZURE_SUBSCRIPTION: e25f6d13-1843-4917-9bb0-f2c2a84acfb5
 AZURE-LOCATION: eastUS

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
     configuration: release
     
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{env.configuration}}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{env.configuration}}
    - name: Publish
      run: dotnet publish --configuration ${{env.configuration}} --output ${{runner.temp}}/publish
    - name: Upload the publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish_artifact
        path: ${{runner.temp}}/publish
        retention-days: 30
    - name: Upload a template artifact
      uses: actions/upload-artifact@v3
      with:
        name: templates_artifact
        path: ./templates/*
        retention-days: 30  

  RG-Job:
    runs-on: ubuntu-latest
    needs: [Build-Job]
    steps:
    - name: Sign in to azure
      uses: azure/login@v1
      with: 
        creds: ${{secrets.AZ_CRED}}
    - name: Create resource group
      uses: azure/cli@v1
      with:
        inlineScript: az group create --location WestEurope --name ${{env.AZURE_RG}}

  Dev-Job:
    runs-on: ubuntu-latest
    environment: dev
    needs: [RG-Job]
    env: 
     AZURE-WEBAPP-NAME: ib-mywebapp-dev
    steps:
    - name: Download template
      uses: actions/download-artifact@v3
      with:
        name: templates_artifact
        path: ${{runner.temp}}/templates
    - name: Sign in to azure
      uses: azure/login@v1
      with: 
        creds: ${{secrets.AZ_CRED}}
    - name: Deploy bicep template 
      uses: azure/arm-deploy@v1
      id: deploywebapp
      with:
        deploymentName: create-webapp
        subscriptionId: ${{env.AZURE_SUBSCRIPTION}}
        resourceGroupName: ${{env.AZURE_RG}}
        template: ${{runner.temp}}/templates/webapp.bicep
        parameters: location=${{env.AZURE-LOCATION}} appName=${{env.AZURE-WEBAPP-NAME}}
    - name: Download publish
      uses: actions/download-artifact@v3
      with:
        name: publish-artifact
        path: ${{runner.temp}}/publish
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{steps.deploywebapp.outputs.webappname}}
        package: ${{runner.temp}}/publish


 