# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI-CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - Readme.md
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
env:
 AZURE_RG: github-actions-staged
 AZURE_SUBSCRIPTION: 7ab090d4-fa2e-4ecf-bc7c-4127b4d582ec
 AZURE-LOCATION: eastUS

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
     configuration: release
     
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{env.configuration}}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{env.configuration}}
    - name: Publish
      run: dotnet publish --configuration ${{env.configuration}} --output ${{runner.temp}}/publish
    - name: Upload the publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish_artifact
        path: ${{runner.temp}}/publish
        retention-days: 30
    - name: Upload a template artifact
      uses: actions/upload-artifact@v3
      with:
        name: templates_artifact
        path: ./templates/*
        retention-days: 30  

  RG-Job:
    runs-on: ubuntu-latest
    needs: [Build-Job]
    steps:
    - uses: azure/login@v1
      name: Sign in to azure
      with: 
        creds: ${{secrets.AZ_CRED}}
    - uses: azure/cli@v1
      name: Create resource group
      with:
        inlineScript: az group create --location WestEurope --name ${{env.AZURE_RG}}

